Historia,1,¿En qué año comenzó la Revolución Francesa?,1789-1799-1805-1815,1789,"Inicio de cambios radicales"
Historia,1,¿Cuál fue la capital del Imperio Romano?,Atenas-Roma-Cartago-Constantinopla,Roma,"Centro del poder romano"
Historia,1,¿Quién fue el líder de la Revolución Rusa en 1917?,Vladimir Lenin-José Stalin-León Trotsky-Nicolás II,Vladimir Lenin,"Figura clave del movimiento"
Historia,1,¿En qué año se firmó la Declaración de Independencia de los Estados Unidos?,1776-1789-1800-1812,1776,"Año de la independencia"
Historia,2,¿Quién fue el último emperador de Rusia?,Pedro el Grande-Nicolás II-Alejandro I-Iván IV,Nicolás II,"Final de la monarquía"
Historia,2,¿Qué evento histórico inició la Edad Moderna?,Descubrimiento de América-Peste Negra-Caída de Constantinopla-Reforma Protestante,Descubrimiento de América,"Descubrimiento significativo"
Historia,2,¿Quién fue la primera persona en circunnavegar la Tierra?,Marco Polo-Ferdinand Magellan-Cristóbal Colón-Vasco de Gama,Ferdinand Magellan,"Viaje alrededor del mundo"
Historia,2,¿Cuál era la capital del Imperio Inca?,Machu Picchu-Qusqu-Pachacámac-Tiahuanaco,Qusqu,"Centro administrativo"
Historia,2,¿Qué tratado puso fin a la Guerra de los Treinta Años?,Tratado de Westfalia-Tratado de Utrecht-Tratado de París-Tratado de Versalles,Tratado de Westfalia,"Europa, siglo XVII"
Historia,3,¿Quién era el líder de los griegos en la Guerra de Troya?,Agamenón-Paris-Héctor-Ulises,Agamenón,"Rey de Micenas"
Historia,3,¿Cuál fue el primer país en otorgar el derecho al voto a las mujeres?,Estados Unidos-Francia-Reino Unido-Nueva Zelanda,Nueva Zelanda,"Avance en derechos"
Historia,3,¿Qué evento marcó el inicio de la Primera Guerra Mundial?,Asesinato de Francisco Fernando-Invasión de Polonia-Batalla de Verdún-Caída de Constantinopla,Asesinato de Francisco Fernando,"Crisis diplomática"
Historia,4,¿Qué evento marcó el fin de la Guerra Fría?,Caída del Muro de Berlín-Revolución Iraní-Invasión de Afganistán-Revolución de terciopelo,Caída del Muro de Berlín,"Cambio geopolítico"
Historia,4,¿Quién fue el arquitecto principal de la Unificación de Italia en el siglo XIX?,Giuseppe Mazzini-Giuseppe Garibaldi-Camilo Benso de Cavour-Victor Emmanuel II,Camilo Benso de Cavour,"Política y diplomacia"
Historia,4,¿Qué emperador romano adoptó el cristianismo como religión oficial del Imperio?,Augusto-Constantino-Nerón-Diocleciano,Constantino,"Edicto en Milán"
Historia,5,¿Cuál fue el nombre de la primera mujer en el espacio?,Sally Ride-Valentina Tereshkova-Christa McAuliffe-Judith Resnik,Valentina Tereshkova,"Astronauta soviética"
Historia,5,¿Qué filósofo griego fue el maestro de Alejandro Magno?,Aristóteles-Sócrates-Platón-Heráclito,Aristóteles,"Estudiante de Platón"
Historia,5,¿Quién fue el rey de Inglaterra durante la Guerra de los Cien Años?,Ricardo Corazón de León-Juan Sin Tierra-Enrique V-Carlos VII,Juan Sin Tierra,"Firma de la Magna Carta"
Historia,6,¿Cuál fue el primer país en lanzar una sonda espacial a la Luna?,Estados Unidos-Unión Soviética-China-India,Unión Soviética,"Carrera espacial"
Historia,6,¿Quién escribió 'El Príncipe'. un tratado político del Renacimiento italiano?,Leonardo da Vinci-Nicolás Maquiavelo-Galileo Galilei-Giordano Bruno,Nicolás Maquiavelo,"Realpolitik"
Historia,6,¿En qué año comenzó la Revolución Industrial en Inglaterra?,1700-1750-1800-1850,1800,"Transformación económica"
Historia,7,¿Cuál era el nombre de la primera civilización de la historia?,Egipto-Mesopotamia-India-China,Mesopotamia,"Ríos Tigris y Éufrates"
Historia,7,¿En qué ciudad italiana tuvo lugar el Renacimiento cultural?,Florencia-Roma-Venecia-Nápoles,Florencia,"Cuna del Humanismo"
Historia,7,¿Qué emperador romano construyó el Coliseo en Roma?,Julio César-Nerón-Trajano-Vespasiano,Vespasiano,Anfiteatro famoso
Historia,8,¿Quién fue el primer emperador romano?,Julio César-Augusto-Tiberio-Calígula,Augusto,Principado
Historia,8,¿Qué acontecimiento marcó el fin de la dinastía Qing en China?,Revolución Xinhai-Guerra del Opio-Guerra Taiping-Rebelión Taiping,Revolución Xinhai,Transición republicana
Historia,8,¿Qué tratado puso fin a la Guerra de los Siete Años?,Tratado de París-Tratado de Madrid-Tratado de Versalles-Tratado de Aquisgrán,Tratado de París,Europa y colonias
Historia,9,¿Quién fue el primer presidente de Argentina?,Bernardino Rivadavia-Juan Manuel de Rosas-Justo José de Urquiza-Carlos Pellegrini,Bernardino Rivadavia,Primer presidente
Historia,9,¿Qué acontecimiento inició la Independencia en Argentina?,Revolución de Mayo-Batalla de Cepeda-Congreso de Tucumán-Expedición Libertadora de Chile y Perú,Revolución de Mayo,Inicio del movimiento
Historia,9,¿Quién fue el líder del movimiento independentista en Argentina?,Manuel Belgrano-José de San Martín-Juan José Castelli-Bernardino Rivadavia,José de San Martín,Cruce de los Andes
Historia,10,¿Quién fue el primer gobernador argentino después de la independencia?,Juan Manuel de Rosas-Justo José de Urquiza-Bartolomé Mitre-Mariano Moreno,Juan Manuel de Rosas,Gobernante post-independencia
Historia,10,¿Cuál fue el primer país en reconocer la independencia de Argentina?,España-Francia-Estados Unidos-Reino Unido,Estados Unidos,Reconocimiento internacional
Historia,10,¿Qué presidente argentino inició la 'Década Infame' en 1930?,Hipólito Yrigoyen-Marcelo T. de Alvear-José Félix Uriburu-Agustín P. Justo,José Félix Uriburu,Golpe de Estado
Historia,11,¿Qué marcó el inicio de la Guerra de las Malvinas en 1982?,Desembarco argentino en las islas-Invasión británica-Incidente de Puerto Argentino-Referéndum de autodeterminación,Desembarco argentino en las islas,Conflicto territorial
Historia,11,¿Quién fue el presidente de Argentina durante la crisis económica de 2001?,Fernando de la Rúa-Néstor Kirchner-Eduardo Duhalde-Cristina Fernández de Kirchner,Fernando de la Rúa,Corralito
Historia,11,¿Qué acontecimiento marcó el final de la dictadura militar en Argentina en 1983?,Elección de Raúl Alfonsín-Juicio a las Juntas-Guerra de las Malvinas-Levantamiento del Estado de Sitio,Elección de Raúl Alfonsín,Retorno a la democracia
Historia,12,¿Qué movimiento político fue liderado por Juan Domingo Perón?,Justicialismo-Radicalismo-Socialismo-Comunismo,Justicialismo,Peronismo
Historia,12,¿Cuál fue la fecha del Golpe de Estado 'Noche de los Bastones Largos'?,28 de junio-29 de mayo-30 de abril-29 de septiembre,29 de mayo,Represión en la universidad
Historia,12,¿Quién fue la figura principal de los 'Montoneros' en los años 70?,Roberto Quieto-Mario Firmenich-Carlos Menem-Ricardo Balbín,Mario Firmenich,Guerrilla urbana
Historia,13,¿Qué presidente argentino firmó el tratado de paz con Chile en 1984?,Leopoldo Galtieri-Jorge Rafael Videla-Raúl Alfonsín-Fernando de la Rúa,Raúl Alfonsín,Acuerdo internacional
Historia,13,¿Quién fue el líder del peronismo entre 1946 y 1955?,Juan Domingo Perón-Arturo Frondizi-Arturo Illia-Pedro Eugenio Aramburu,Juan Domingo Perón,Segunda presidencia
Historia,13,¿Cuál fue el nombre del plan económico de Domingo Cavallo en los 90?,Plan Austral-Plan Bonex-Plan Primavera-Plan de Convertibilidad,Plan de Convertibilidad,Era de la convertibilidad
Historia,14,¿Qué presidente argentino firmó el tratado de libre comercio con Chile en 1991?,Carlos Menem-Fernando de la Rúa-Néstor Kirchner-Eduardo Duhalde,Carlos Menem,Apertura económica
Historia,14,¿Quién fue el líder de la revolución que derrocó a Perón en 1955?,Arturo Frondizi-Armando Frondizi-Arturo Illia-Pedro Eugenio Aramburu,Pedro Eugenio Aramburu,Golpe militar
Historia,14,¿Cuál fue el nombre de la operación militar para la recuperación de las Islas Malvinas en 1982?,Operación Cóndor-Operación Rosario-Operación Soberanía-Operación Independencia,Operación Rosario,Desembarco argentino
Historia,15,¿Quién fue el presidente argentino durante la Guerra de las Malvinas en 1982?,Carlos Menem-Leopoldo Galtieri-Raúl Alfonsín-Fernando de la Rúa,Leopoldo Galtieri,Conflicto bélico
Historia,15,¿Qué figura argentina fue presidente de la Asamblea General de las Naciones Unidas en 1948?,Carlos Saavedra Lamas-Juan Domingo Perón-José Figueres-Arturo Frondizi,Carlos Saavedra Lamas,Premio Nobel de la Paz
Historia,15,¿Quién fue el líder del movimiento obrero 'La Forestal' en los años 20?,Luis Dellepiane-Ángel Borlenghi-Agustín Tosco-Luis Gay,Luis Dellepiane,Lucha sindical
Deportes,1,¿En qué deporte compite un luchador de sumo?,Boxeo-Lucha libre-Sumo-Judo,Sumo,"Combate en un dohyō"
Deportes,1,¿Quién es considerado el mejor jugador de fútbol de todos los tiempos?,Lionel Messi-Cristiano Ronaldo-Diego Maradona-Pelé,Diego Maradona,"La 'Mano de Dios'"
Deportes,1,¿En qué deporte se destaca un gimnasta en una barra de equilibrio?,Natación-Gimnasia artística-Atletismo-Ciclismo,Gimnasia artística,"Ejercicio de destreza"
Deportes,1,¿Cuántos jugadores componen un equipo de béisbol durante un partido?,7-9-11-5,9,"Posiciones defensivas"
Deportes,1,¿Qué jugador de tenis ganó más títulos de Grand Slam en la historia?,Roger Federer-Rafael Nadal-Novak Djokovic-Pete Sampras,Roger Federer,"Suizo de raqueta"
Deportes,2,¿Cuál es el evento deportivo más grande del mundo en términos de audiencia televisiva?,Juegos Olímpicos-Copa Mundial de Fútbol-Super Bowl-Tour de Francia,Copa Mundial de Fútbol,"Cada cuatro años"
Deportes,2,¿En qué país se originó el deporte del rugby?,Inglaterra-Escocia-Irlanda-Gales,Inglaterra,"Hogar de los leones"
Deportes,2,¿Qué equipo ganó la primera Copa Mundial de Fútbol en 1930?,Argentina-Uruguay-Brasil-Italia,Uruguay,"País sudamericano"
Deportes,2,¿En qué deporte se destaca un nadador en una prueba de estilo libre?,Atletismo-Ciclismo-Natación-Esgrima,Natación,"Crol en piscina"
Deportes,2,¿Cuántos sets componen un partido de tenis de Grand Slam masculino?,3-4-5-6,5,"Partido extenso"
Deportes,3,¿En qué deporte se compite por el Trofeo Larry O'Brien?,Baloncesto-Fútbol americano-Hockey sobre hielo-Béisbol,Baloncesto,"Canasta y red"
Deportes,3,¿Quién fue el primer atleta en correr una milla en menos de cuatro minutos?,Roger Bannister-Usain Bolt-Jesse Owens-Carl Lewis,Roger Bannister,"Logro histórico"
Deportes,3,¿Cuál es el deporte principal en los Juegos Paralímpicos?,Atletismo-Natación-Tiro con arco-Ciclismo,Atletismo,"Competencia adaptada"
Deportes,3,¿Cuál es el equipo de fútbol más exitoso de la historia de la Copa Libertadores?,River Plate-Boca Juniors-Independiente-Peñarol,Independiente,"Club de Buenos Aires"
Deportes,3,¿Qué golfista es conocido como 'El Tigre'?,Arnold Palmer-Jack Nicklaus-Tiger Woods-Rory McIlroy,Tiger Woods,"Dominio en greens"
Deportes,4,¿En qué país se originó el deporte del polo?,Argentina-India-Reino Unido-Francia,India,"Juego ecuestre"
Deportes,4,¿Quién ganó la medalla de oro en baloncesto masculino en los Juegos Olímpicos de 1992?,Estados Unidos-España-Argentina-Croacia,Estados Unidos,"Dream Team"
Deportes,4,¿En qué deporte compite un boxeador en un ring?,Tenis-Boxeo-Esgrima-Judo,Boxeo,"Guantes y cuadrilátero"
Deportes,4,¿Qué nadador estadounidense ganó siete medallas de oro en los Juegos Olímpicos de 1972?,Mark Spitz-Michael Phelps-Johnny Weissmuller-Ian Thorpe,Mark Spitz,"Dominio en piscina"
Deportes,4,¿Cuál es el equipo más laureado en la historia de la NBA?,Chicago Bulls-Los Angeles Lakers-Boston Celtics-Golden State Warriors,Boston Celtics,"Camiseta verde y blanca"
Deportes,5,¿En qué deporte compite un velocista en los Juegos Olímpicos?,Atletismo-Natación-Ciclismo-Esgrima,Atletismo,"Carreras cortas"
Deportes,5,¿Quién fue el primer piloto de Fórmula 1 en ganar siete campeonatos mundiales?,Ayrton Senna-Lewis Hamilton-Michael Schumacher-Juan Manuel Fangio,Michael Schumacher,"Leyenda argentina"
Deportes,5,¿Qué tenista argentino ganó el Abierto de Estados Unidos en 2009?,Guillermo Vilas-David Nalbandian-Juan Martín del Potro-Gastón Gaudio,Juan Martín del Potro,"Torre de Tandil"
Deportes,5,¿En qué deporte compite un atleta en una maratón?,Atletismo-Natación-Ciclismo-Esgrima,Atletismo,"Carrera de resistencia"
Deportes,5,¿Cuál es el equipo más antiguo en la liga argentina de fútbol?,Boca Juniors-River Plate-Independiente-Racing Club,River Plate,"Apodo de 'Millonarios'"
Deportes,6,¿En qué deporte compite un jinete en una carrera de obstáculos?,Hípica-Atletismo-Ciclismo-Natación,Hípica,"Salto y doma"
Deportes,6,¿Qué boxeador argentino fue campeón mundial en cinco categorías diferentes?,Carlos Monzón-Marcelo Bielsa-Sergio Martínez-Juan Martín Coggi,Sergio Martínez,"Maravilla"
Deportes,6,¿Quién fue el futbolista argentino conocido como 'El Pibe de Oro'?,Lionel Messi-Diego Maradona-Gabriel Batistuta-Carlos Tevez,Diego Maradona,"Mano de Dios"
Deportes,6,¿En qué deporte compite un esgrimista en una pista de combate?,Boxeo-Esgrima-Natación-Atletismo,Esgrima,"Florete y sable"
Deportes,6,¿Qué tenista argentino ganó el Abierto de Francia en 1977?,Guillermo Vilas-Juan Martín del Potro-David Nalbandian-José Luis Clerc,Guillermo Vilas,"Máquina de zurda"
Deportes,7,¿En qué deporte compite un golfista en un campo de 18 hoyos?,Golf-Tenis-Natación-Ciclismo,Golf,"Drive y putt"
Deportes,7,¿Qué jugador argentino fue campeón del mundo en 1978?,Mario Kempes-Diego Maradona-Gabriel Batistuta-Lionel Messi,Mario Kempes,"Goleador en casa"
Deportes,7,¿En qué deporte compite un esquiador en una pista nevada?,Esquí-Natación-Atletismo-Ciclismo,Esquí,"Deslizamiento y slalom"
Deportes,7,¿Qué piloto argentino ganó el Campeonato Mundial de Rally en 1980 y 1982?,Carlos Reutemann-José Froilán González-Marcos Di Palma-Jorge Raúl Recalde,Jorge Raúl Recalde,"Velocidad en tierra"
Deportes,7,¿En qué deporte compite un jugador en una cancha de césped?,Fútbol-Tenis-Hockey sobre césped-Rugby,Tenis,"Raqueta y red"
Deportes,8,¿En qué deporte compite un regatista en una competencia náutica?,Vela-Surf-Remo-Canotaje,Vela,"Viento y marea"
Deportes,8,¿Qué equipo argentino ganó la Copa Libertadores de América en 2007?,River Plate-Boca Juniors-San Lorenzo-Estudiantes,Boca Juniors,"Club de La Plata"
Deportes,8,¿En qué deporte compite un taekwondista en un combate?,Taekwondo-Judo-Lucha libre-Boxeo,Taekwondo,"Artes marciales"
Deportes,8,¿Qué piloto argentino ganó el Campeonato Mundial de Fórmula 1 en 1951 y 1954?,Juan Manuel Fangio-Carlos Reutemann-José Froilán González-Guillermo Vilas,Juan Manuel Fangio,"Máquina argentina"
Deportes,9,¿En qué deporte se utiliza una pista de hielo para competir?,Hockey sobre hielo-Patín artístico-Esquí-Bobsleigh,Hockey sobre hielo,"Stick y puck"
Deportes,9,¿Qué tenista argentino ganó el Abierto de Estados Unidos en 2009?,Guillermo Vilas-David Nalbandian-Juan Martín del Potro-Gastón Gaudio,Juan Martín del Potro,"Torre de Tandil"
Deportes,9,¿En qué deporte se utiliza una cancha de arcilla para jugar?,Tenis-Bádminton-Fútbol-Hockey sobre césped,Tenis,"Pelota y raqueta"
Deportes,9,¿Qué equipo argentino ganó la Copa Intercontinental en 1979?,Boca Juniors-Independiente-River Plate-Estudiantes,Independiente,"Rey de Copas"
Deportes,10,¿En qué deporte compite un golfista en un campo de 18 hoyos?,Golf-Tenis-Natación-Ciclismo,Golf,"Drive y putt"
Deportes,10,¿Qué jugador argentino fue campeón del mundo en la Copa Mundial de Fútbol de 1978?,Mario Kempes-Diego Maradona-Gabriel Batistuta-Lionel Messi,Mario Kempes,"Goleador en casa"
Deportes,10,¿En qué deporte compite un esquiador en una pista nevada?,Esquí-Natación-Atletismo-Ciclismo,Esquí,"Deslizamiento y slalom"
Deportes,10,¿Qué piloto argentino ganó el Campeonato Mundial de Rally en 1980 y 1982?,Carlos Reutemann-José Froilán González-Marcos Di Palma-Jorge Raúl Recalde,Jorge Raúl Recalde,"Velocidad en tierra"
Deportes,11,¿En qué deporte compite un jugador en una cancha de césped?,Fútbol-Tenis-Hockey sobre césped-Rugby,Tenis,"Raqueta y red"
Deportes,11,¿Qué atleta argentino ganó la medalla de oro en los Juegos Olímpicos de Atenas 2004 en básquetbol?,Manu Ginóbili-Gabriela Sabatini-Carlos Delfino-Andrés Nocioni,Manu Ginóbili,"NBA y selección"
Deportes,11,¿En qué deporte compite un gimnasta en una barra fija?,Lucha libre-Boxeo-Gimnasia artística-Judo,Gimnasia artística,"Destreza y equilibrio"
Deportes,11,¿Qué equipo argentino ganó la Copa Sudamericana en 2017?,River Plate-Boca Juniors-Independiente-San Lorenzo,Independiente,"Rey de Copas"
Deportes,12,¿En qué deporte compite un nadador en una prueba de estilo mariposa?,Natación-Atletismo-Esquí-Ciclismo,Natación,"Movimiento acuático"
Deportes,12,¿Qué tenista argentino ganó la medalla de oro en los Juegos Olímpicos de Atenas 2004 en tenis?,Guillermo Coria-Gastón Gaudio-Juan Martín del Potro-David Nalbandian,David Nalbandian,"Torre de Tandil"
Deportes,12,¿En qué deporte se destaca un atleta en una maratón?,Atletismo-Natación-Ciclismo-Esgrima,Atletismo,"Carrera de resistencia"
Deportes,12,¿Qué equipo argentino ganó la Recopa Sudamericana en 2015?,River Plate-Boca Juniors-Independiente-San Lorenzo,River Plate,"Campeón continental"
Deportes,13,¿En qué deporte compite un karateka en un combate?,Karate-Judo-Lucha libre-Boxeo,Karate,"Arte marcial"
Deportes,13,¿Qué atleta argentino ganó la medalla de oro en los Juegos Olímpicos de Atenas 2004 en hockey sobre césped?,Luciana Aymar-Carlos Tevez-Gabriela Sabatini-Ginette Reynal,Luciana Aymar,"Leona de oro"
Deportes,13,¿En qué deporte compite un tenista en una cancha de césped artificial?,Fútbol-Tenis-Hockey sobre césped-Rugby,Tenis,"Pelota amarilla"
Deportes,13,¿Qué equipo argentino ganó la Copa América en 2021?,Brasil-Colombia-Chile-Argentina,Argentina,"Copa en casa"
Deportes,14,¿En qué deporte se destaca un ciclista en una prueba de velocidad?,Atletismo-Natación-Ciclismo-Esgrima,Ciclismo,"Ruedas y pedal"
Deportes,14,¿Qué futbolista argentino ganó el Balón de Oro en 1978?,Diego Maradona-Alfredo Di Stéfano-Omar Sívori-Daniel Passarella,Omar Sívori,"10 mágico"
Deportes,14,¿En qué deporte compite un jugador en una cancha de tierra batida?,Fútbol-Tenis-Hockey sobre césped-Rugby,Tenis,"Pelota amarilla"
Deportes,14,¿Qué equipo argentino ganó la Supercopa Sudamericana en 1997?,River Plate-Boca Juniors-Independiente-Vélez Sarsfield,Vélez Sarsfield,"Campeón continental"
Deportes,15,¿En qué deporte se destaca un nadador en una prueba de estilo espalda?,Natación-Atletismo-Esquí-Ciclismo,Natación,"Movimiento acuático"
Deportes,15,¿Qué boxeador argentino fue campeón mundial en cinco categorías diferentes?,Carlos Monzón-Marcelo Bielsa-Sergio Martínez-Juan Martín Coggi,Sergio Martínez,"Maravilla"
Deportes,15,¿Quién fue el futbolista argentino conocido como 'El Pibe de Oro'?,Lionel Messi-Diego Maradona-Gabriel Batistuta-Carlos Tevez,Diego Maradona,"Mano de Dios"
Deportes,15,¿En qué deporte se compite por el Trofeo Larry O'Brien?,Baloncesto-Fútbol americano-Hockey sobre hielo-Béisbol,Baloncesto,"Canasta y red"
Entretenimiento,1,¿Qué actor fue James Bond en "Goldfinger" de 1964?,Sean Connery-Roger Moore-Pierce Brosnan-Daniel Craig,Sean Connery,"Icono británico"
Entretenimiento,1,¿En qué saga aparece Luke Skywalker?,Star Wars-Matrix-Jurassic Park-Marvel,Star Wars,"Galaxia muy, muy lejana"
Entretenimiento,1,¿Qué personaje de Disney tiene amigo Flounder y cangrejo Sebastián?,Ariel-Bella-Cenicienta-Moana,Ariel,"Bajo el mar"
Entretenimiento,1,¿Qué grupo musical lanzó "Abbey Road" en 1969?,The Beatles-The Beach Boys-Led Zeppelin-The Rolling Stones,The Beatles,"Calle mítica"
Entretenimiento,1,¿Quién dirigió "El Padrino"?,Francis Ford Coppola-Martin Scorsese-Steven Spielberg-Quentin Tarantino,Francis Ford Coppola,"Familia Corleone"
Entretenimiento,2,¿En qué película Forrest Gump dice "La vida es como caja de chocolates"?,Forrest Gump-Titanic-Matrix-American Beauty,Forrest Gump,"Corre, Forrest, corre"
Entretenimiento,2,¿Quién dirigió "Tiburón"- "E.T." y "Parque Jurásico"?,George Lucas-Steven Spielberg-Martin Scorsese-Ridley Scott,Steven Spielberg,"Cineasta de Hollywood"
Entretenimiento,2,¿Quién fue Jack Dawson en "Titanic"?,Leonardo DiCaprio-Brad Pitt-Tom Cruise-Matt Damon,Leonardo DiCaprio,"Rey del mundo"
Entretenimiento,2,¿Dónde se desarrolla serie Springfield?,Padre de familia-Los Simpson-Futurama-American Dad,Los Simpson,"D'oh!"
Entretenimiento,2,¿Quién fue Batman en "Batman Begins" 2005?,Christian Bale-Michael Keaton-George Clooney-Ben Affleck,Christian Bale,"Caballero oscuro"
Entretenimiento,3,¿En qué película Disney protagonista rana?,Mulan-Enredados-La Princesa y el Sapo-Frozen,La Princesa y el Sapo,"Nueva Orleans"
Entretenimiento,3,¿Quién fue Iron Man en Marvel?,Chris Hemsworth-Chris Evans-Robert Downey Jr.-Mark Ruffalo,Robert Downey Jr.,"Genio, multimillonario"
Entretenimiento,3,¿Quién cantó "Skyfall" para James Bond?,Adele-Taylor Swift-Beyoncé-Rihanna,Adele,"Se derrite al cantar"
Entretenimiento,3,¿En qué película Tyler Durden dice "No eres especial"?,El Club de la Pelea-El Resplandor-American Psycho-Inception,El Club de la Pelea,"Reglas del club"
Entretenimiento,3,¿Quién dirigió "Pulp Fiction"/ "Kill Bill" y "Reservoir Dogs"?,Quentin Tarantino-Christopher Nolan-Martin Scorsese-David Fincher,Quentin Tarantino,"Violencia estilizada"
Entretenimiento,4,¿Qué serie narra Walter White- profesor narcotraficante?,Breaking Bad-Stranger Things-The Crown-House of Cards,Breaking Bad,"I'm the one who"
Entretenimiento,4,¿Quién fue Jack Sparrow en "Pirates of the Caribbean"?,Johnny Depp-Orlando Bloom-Keira Knightley-Geoffrey Rush,Johnny Depp,"Capitán excéntrico"
Entretenimiento,4,¿Qué película de Nolan explora sueños?,Inception-Interstellar-Memento-The Dark Knight,Inception,"Laberinto mental"
Entretenimiento,4,¿En qué película Tony Montana dice "Primero pelota- luego cruz"?,Scarface-Goodfellas-The Godfather-Casino,Scarface,"Say hello to my"
Entretenimiento,4,¿Dónde caminantes blancos amenazan?,Stranger Things-Westworld-Juego de Tronos-Breaking Bad,Juego de Tronos,"Winter is coming"
Entretenimiento,5,¿Qué película Ridley Scott sigue astronautas planeta?,Blade Runner-Prometheus-Alien-Interstellar,Alien,"En el espacio"
Entretenimiento,5,¿Quién fue Neo en "The Matrix" trilogía?,Keanu Reeves-Hugo Weaving-Laurence Fishburne-Carrie-Anne Moss,Keanu Reeves,"La elección"
Entretenimiento,5,¿Quién cantó "Let It Go" de "Frozen"?,Demi Lovato-Idina Menzel-Taylor Swift-Adele,Idina Menzel,"Libre soy"
Entretenimiento,5,¿En qué película Michael Corleone dice "Mantén amigos- enemigos más cerca"?,Goodfellas-The Godfather-Scarface-Heat,The Godfather,"Familia Corleone"
Entretenimiento,5,¿Dónde humanos interactúan androides?,Westworld-Battlestar Galactica-Doctor Who-Black Mirror,Westworld,"Derechos sintéticos"
Entretenimiento,6,¿En qué película Danny Torrance dice "Aquí está Johnny"?,El Resplandor-Poltergeist-El Exorcista-Carrie,El Resplandor,"Hotel maldito"
Entretenimiento,6,¿Quién fue Joker en "The Dark Knight"?,Joaquin Phoenix-Heath Ledger-Jack Nicholson-Cesar Romero,Heath Ledger,"Caos y anarquía"
Entretenimiento,6,¿Dónde familia Springfield trabaja planta nuclear?,Padre de familia-Los Simpson-Futurama-South Park,Los Simpson,"¡Ay, caramba!"
Entretenimiento,6,¿En qué película Hannibal Lecter dice "Manera curiosa ver vida querido"?,El Silencio de los Inocentes-Seven-American Psycho-El Resplandor,El Silencio de los Inocentes,"Caníbal inteligente"
Entretenimiento,6,¿Quién dirigió "El Resplandor"- "2001: Odisea del espacio" y "La Naranja Mecánica"?,David Lynch-Stanley Kubrick-Alfred Hitchcock-Quentin Tarantino,Stanley Kubrick,"Maestro del"
Entretenimiento,7,¿En qué película Luke Skywalker descubre Darth Vader padre?,El Imperio Contraataca-El Retorno del Jedi-La Amenaza Fantasma-El Despertar de la Fuerza,El Imperio Contraataca,"Yo soy tu"
Entretenimiento,7,¿Quién fue Gandalf en "El Señor de los Anillos"?,Ian McKellen-Sean Connery-Patrick Stewart-Christopher Lee,Ian McKellen,"Mago sabio"
Entretenimiento,7,¿En qué película Tarantino personajes bailan antes tiroteo?,Pulp Fiction-Kill Bill-Reservoir Dogs-Inglourious Basterds,Pulp Fiction,"Bailar entre"
Entretenimiento,7,¿Dónde política y guerras Trono Hierro Siete Reinos?,Breaking Bad-Stranger Things-Game of Thrones-Westworld,Game of Thrones,"Basada en libros"
Entretenimiento,8,¿Qué actor interpretó a Walter White en "Breaking Bad"?,Bryan Cranston-Aaron Paul-Bob Odenkirk-Dean Norris,Bryan Cranston,"Mr. White"
Entretenimiento,8,¿En qué película James Bond dice "Mi nombre es Bond- "James Bond" por primera vez?,Dr. No-Goldfinger-From Russia-Thunderball,Dr. No,"Agente secreto"
Entretenimiento,8,¿Qué director es conocido por "El Orfanato" y "Lo Imposible"?,Guillermo del Toro-J.A. Bayona-Alfonso Cuarón-Alejandro Amenábar,J.A. Bayona,"Terror y emociones"
Entretenimiento,8,¿En qué película Rick Deckard caza androides?,Blade Runner-Terminator-Mad Max-The Matrix,Blade Runner,"Los replicantes"
Entretenimiento,8,¿Qué serie narra la vida de un químico convertido en narcotraficante?,Better Call Saul-Breaking Bad-The Walking Dead-House of Cards,Breaking Bad,"I am the one who knocks"
Entretenimiento,9,¿Qué película de Spielberg cuenta la historia de un extraterrestre perdido en la Tierra?,Close Encounters-Jurassic Park-E.T.-War of the Worlds,E.T.,"Teléfono"
Entretenimiento,9,¿Qué actor interpretó a Jack en "El Resplandor"?,Jack Nicholson-Heath Ledger-Joaquin Phoenix-Leonardo DiCaprio,Jack Nicholson,"Aquí está Johnny"
Entretenimiento,9,¿En qué película de Tarantino los personajes se refugian en una cabaña durante una tormenta de nieve?,Pulp Fiction-Kill Bill-Hateful Eight-Reservoir Dogs,Hateful Eight,"Ocho odiosos"
Entretenimiento,9,¿Qué serie narra las aventuras de un grupo de supervivientes en un mundo posapocalíptico lleno de caminantes?,Lost-Stranger Things-Breaking Bad-The Walking Dead,The Walking Dead,"Caminantes"
Entretenimiento,9,¿Qué actor interpretó a Deadpool en Marvel?,Ryan Reynolds-Chris Hemsworth-Robert Downey-Chris Evans,Ryan Reynolds,"Antihéroe bocón"
Entretenimiento,10,¿En qué película Rocky Balboa dice "¡Adriaaaan!"?,Rocky-Creed-Raging Bull-Million Dollar Baby,Rocky,"Sueño de boxeo"
Entretenimiento,10,¿Qué actor interpretó a Han Solo en la saga de Star Wars?,Mark Hamill-Harrison Ford-Alec Guinness-Anthony Daniels,Harrison Ford,"Contrabandista galáctico"
Entretenimiento,10,¿Qué película de Scorsese cuenta la historia de un boxeador llamado Jake LaMotta?,Goodfellas-Raging Bull-Taxi Driver-Casino,Raging Bull,"Toro salvaje"
Entretenimiento,10,¿En qué serie la familia Stark lucha por el Trono de Hierro?,Westworld-Black Mirror-Juego de Tronos-The Crown,Juego de Tronos,"Winter is coming"
Entretenimiento,10,¿Qué director es conocido por "Taxi Driver", "El Lobo de Wall Street" y "Toro Salvaje"?,Quentin Tarantino-Martin Scorsese-Steven Spielberg-Christopher Nolan,Martin Scorsese,"Cineasta neoyorquino"
Entretenimiento,11,¿En qué película Tony Montana dice "Dame la pasta chico"?,Scarface-Goodfellas-American Gangster-Blow,Scarface,"Montaña de polvo blanco"
Entretenimiento,11,¿Qué actor interpretó a Gandalf en "El Hobbit"?,Sean Connery-Ian McKellen-Patrick Stewart-Christopher Lee,Ian McKellen,"Mago gris"
Entretenimiento,11,¿En qué película de Nolan el personaje Dom Cobb es un ladrón de secretos?,Inception-Interstellar-Memento-The Prestige,Inception,"Arquitectura de la mente"
Entretenimiento,11,¿Qué serie narra la vida de una familia que lidera un imperio musical en Nueva York?,Empire-Nashville-Glee-Power,Empire,"Rey de la música"
Entretenimiento,11,¿Qué actor interpretó a James Bond en "Casino Royale" de 2006?,Daniel Craig-Pierce Brosnan-Roger Moore-Sean Connery,Daniel Craig,"Agente 007"
Entretenimiento,12,¿En qué película Atticus Finch defiende a un hombre afroamericano acusado injustamente?,Doce Hombres-Algunos Hombres-Matar a un Ruiseñor-En el Nombre del Padre,Matar a un Ruiseñor,"Justicia en el sur"
Entretenimiento,12,¿Qué actor interpretó a Jack en "Titanic"?,Leonardo DiCaprio-Johnny Depp-Brad Pitt-Orlando Bloom,Leonardo DiCaprio,"Rey del mundo"
Entretenimiento,12,¿En qué película de Tarantino los personajes están atrapados en un almacén de diamantes?,Reservoir Dogs-Pulp Fiction-Kill Bill-Jackie Brown,Reservoir Dogs,"Robo fallido"
Entretenimiento,12,¿Qué serie sigue la vida de un químico convertido en narcotraficante llamado Walter White?,Better Call Saul-Breaking Bad-Mad Men-The Sopranos,Breaking Bad,"Yo soy el que golpea"
Entretenimiento,12,¿Qué director es conocido por "Django sin Cadenas"- "Kill Bill" y "Bastardos sin Gloria"?,Quentin Tarantino-Martin Scorsese-Steven Spielberg-Christopher Nolan,Quentin Tarantino,"Violencia estilizada"
Entretenimiento,13,¿En qué película Maximus dice "En esta vida o en la próxima lo juro por todo lo que he perdido nunca volveré a perder la libertad"?,Gladiator-Troy-300-Spartacus,Gladiator,"Are you not entertained?"
Entretenimiento,13,¿Qué actor interpretó a Tony Stark/Iron Man en Marvel?,Chris Evans-Chris Hemsworth-Robert Downey-Mark Ruffalo,Robert Downey,"Genio, multimillonario, playboy, filántropo"
Entretenimiento,13,¿En qué película Rick Deckard es un cazador de androides?,Blade Runner-Terminator-Mad Max-The Matrix,Blade Runner,"Los replicantes"
Entretenimiento,13,¿Qué serie narra la vida de una familia de mafiosos en Nueva Jersey?,The Sopranos-Breaking Bad-Boardwalk Empire-Mad Men,The Sopranos,"Familia criminal"
Entretenimiento,13,¿Qué actor interpretó a Batman en la trilogía de Nolan?,Christian Bale-Michael Keaton-George Clooney-Ben Affleck,Christian Bale,"El caballero oscuro"
Entretenimiento,14,¿En qué película Luke Skywalker descubre que Darth Vader es su padre?,El Imperio Contraataca-El Retorno del Jedi-La Amenaza Fantasma-El Despertar de la Fuerza,El Imperio Contraataca,"Yo soy tu padre"
Entretenimiento,14,¿Qué actor interpretó a Neo en la trilogía de "The Matrix"?,Keanu Reeves-Hugo Weaving-Laurence Fishburne-Carrie-Anne Moss,Keanu Reeves,"La elección"
Entretenimiento,14,¿Qué cantante interpretó la canción "Let It Go" de "Frozen"?,Demi Lovato-Idina Menzel-Taylor Swift-Adele,Idina Menzel,"Libre soy"
Entretenimiento,14,¿En qué película Michael Corleone dice "Mantén a tus amigos cerca pero a tus enemigos aún más cerca"?,Goodfellas-The Godfather-Scarface-Heat,The Godfather,"Familia Corleone"
Entretenimiento,14,¿Qué serie se desarrolla en un futuro donde los humanos interactúan con androides?,Westworld-Battlestar Galactica-Doctor Who-Black Mirror,Westworld,"Derechos sintéticos"
Entretenimiento,15,¿En qué película Danny Torrance dice "Aquí está Johnny"?,El Resplandor-Poltergeist-El Exorcista-Carrie,El Resplandor,"Hotel maldito"
Entretenimiento,15,¿Qué actor interpretó a Joker en "The Dark Knight"?,Joaquin Phoenix-Heath Ledger-Jack Nicholson-Cesar Romero,Heath Ledger,"Caos y anarquía"
Entretenimiento,15,¿Qué serie narra las aventuras de una familia en Springfield donde el protagonista trabaja en la planta nuclear?,Padre de familia-Los Simpson-Futurama-South Park,Los Simpson,"¡Ay, caramba!"
Geografía,1,¿Cuál es el río más largo del mundo?,Nilo-Amazonas-Yangtsé-Misisipi,Amazonas,"Fluye por América del Sur"
Geografía,1,¿En qué continente se encuentra el desierto del Sahara?,África-Asia-Oceanía-América,África,"Gran extensión árida"
Geografía,1,¿Cuál es la capital de Francia?,Londres-Berlín-París-Madrid,París,"Ciudad del amor"
Geografía,1,¿Qué país es conocido como el país de los mil lagos?,Canadá-Finlandia-Rusia-Noruega,Finlandia,"País escandinavo"
Geografía,1,¿Cuál es la montaña más alta del mundo?,Monte Everest-Aconcagua-Mont Blanc-K2,Monte Everest,"Cima en el Himalaya"
Geografía,2,¿En qué país se encuentra el Taj Mahal?,India-China-Japón-Indonesia,India,"Palacio de mármol"
Geografía,2,¿Cuál es el río que atraviesa la ciudad de Londres?,Támesis-Sena-Dniéper-Danubio,Támesis,"Capital británica"
Geografía,2,¿Qué país es conocido como el país de los canguros?,Canadá-Australia-Nueva Zelanda-Sudáfrica,Australia,"Animal emblemático"
Geografía,2,¿En qué océano se encuentra la isla de Madagascar?,Océano Atlántico-Océano Índico-Océano Pacífico-Mar Mediterráneo,Océano Índico,"Gran isla africana"
Geografía,2,¿Cuál es el país más grande del mundo por área terrestre?,Rusia-Canadá-China-Estados Unidos,Rusia,"Extensión transcontinental"
Geografía,3,¿Cuál es la cordillera más larga del mundo?,Himalayas-Montañas Rocosas-Cordillera de los Andes-Alpes,Cordillera de los Andes,"América del Sur"
Geografía,3,¿En qué país se encuentra el Gran Cañón del Colorado?,Estados Unidos-Canadá-México-Australia,Estados Unidos,"Parque nacional"
Geografía,3,¿Qué río atraviesa la ciudad de Roma?,Ródano-Sena-Tíber-Dniéper,Tíber,"Capital italiana"
Geografía,3,¿Cuál es la ciudad más poblada del mundo?,Tokio-Mumbai-Nueva York-Shanghái,Tokio,"Megalópolis asiática"
Geografía,3,¿En qué país se encuentra la Gran Barrera de Coral?,Australia-Brasil-Filipinas-Tanzania,Australia,"Arrecife coralino"
Geografía,4,¿Cuál es la capital de Argentina?,Santiago de Chile-Montevideo-Asunción-Buenos Aires,Buenos Aires,"Ciudad portuaria"
Geografía,4,¿Qué país tiene forma de bota en el mapa de Europa?,Francia-Alemania-Italia-España,Italia,"Península del Mediterráneo"
Geografía,4,¿En qué país se encuentra el canal de Panamá?,Colombia-Costa Rica-Panamá-Nicaragua,Panamá,"Conexión entre océanos"
Geografía,4,¿Qué montaña es conocida como la "Montaña de la Mesa" y está ubicada en Sudáfrica?,Monte Everest-Aconcagua-Kilimanjaro-Table Mountain,Table Mountain,"Ciudad del Cabo"
Geografía,4,¿En qué país se encuentra el Parque Nacional de Yellowstone?,Estados Unidos-Canadá-Australia-Chile,Estados Unidos,"Geiseres y vida salvaje"
Geografía,5,¿Cuál es el mayor archipiélago del mundo por número de islas?,Hawái-Filipinas-Japón-Indonesia,Indonesia,"País insular"
Geografía,5,¿En qué país se encuentra la ciudad de Machu Picchu?,Chile-Perú-Bolivia-Ecuador,Perú,"Ciudadela inca"
Geografía,5,¿Cuál es el lago más profundo del mundo?,Lago Ness-Lago Baikal-Lago Titicaca-Lago Victoria,Lago Baikal,"Siberia"
Geografía,5,¿En qué país se encuentra la Torre Eiffel?,Italia-España-Francia-Portugal,Francia,"Símbolo de París"
Geografía,5,¿Qué desierto es conocido como el más árido del mundo?,Desierto del Sáhara-Desierto de Gobi-Desierto de Atacama-Desierto de Mojave,Desierto de Atacama,"América del Sur"
Geografía,6,¿Cuál es la isla más grande del mundo?,Groenlandia-Australia-Nueva Guinea-Borneo,Groenlandia,"Territorio danés"
Geografía,6,¿En qué país se encuentra el Parque Nacional de Yellowstone?,Estados Unidos-Canadá-Australia-Chile,Estados Unidos,"Geiseres y vida salvaje"
Geografía,6,¿Qué montaña es conocida como la "Montaña de la Mesa" y está ubicada en Sudáfrica?,Monte Everest-Aconcagua-Kilimanjaro-Table Mountain,Table Mountain,"Ciudad del Cabo"
Geografía,7,¿Cuál era el nombre antiguo de Estambul?,Constantinopla-Byzantium-Smyrna-Ephesus,Constantinopla,"Ciudad histórica"
Geografía,7,¿En qué país se encuentra la Gran Muralla China?,Japón-China-Corea del Sur-India,China,"Megaestructura defensiva"
Geografía,7,¿Cuál es el río más largo de América del Sur?,Amazonas-Orinoco-Paraná-Magdalena,Amazonas,"Selva y caudal"
Geografía,8,¿Cuál es el país más pequeño del mundo por área?,Vaticano-Mónaco-Nauru-San Marino,Vaticano,"Sede papal"
Geografía,8,¿En qué país se encuentra la ciudad de Petra, conocida por sus antiguas construcciones talladas en roca?,Jordania-Egipto-Israel-Líbano,Jordania,"Ciudad rosa"
Geografía,8,¿Cuál es el volcán más alto del mundo?,Kilauea-Mauna Kea-Ojos del Salado-Monte Fuji,Ojos del Salado,"Cordillera de los Andes"
Geografía,9,¿En qué país se encuentra la ciudad de Kioto, conocida por ser la antigua capital imperial de Japón?,China-Corea del Sur-Japón-Tailandia,Japón,"Cultura y tradición"
Geografía,9,¿Cuál es el río más largo de Europa?,Volga-Danubio-Sena-Támesis,Volga,"Rusia y caudal"
Geografía,9,¿Qué país se encuentra en la península escandinava?,Dinamarca-Noruega-Suecia-Finlandia,Suecia,"Abetos y lagos"
Geografía,10,¿Cuál es el mayor lago de agua dulce del mundo por volumen?,Lago Baikal-Lago Victoria-Lago Superior-Lago Titicaca,Lago Baikal,"Siberia oriental"
Geografía,10,¿En qué país se encuentra el desierto del Kalahari?,Sudáfrica-Angola-Zambia-Namibia,Sudáfrica,"África austral"
Geografía,10,¿Cuál es la capital más alta del mundo?,La Paz-Bogotá-Quito-Sucre,La Paz,"Ciudad andina"
Geografía,11,¿En qué país se encuentra la ciudad de Vancouver, conocida por su belleza natural y su puerto importante?,Canadá-Estados Unidos-México-Argentina,Canadá,"Costa del Pacífico"
Geografía,11,¿Cuál es la isla más grande del mundo?,Groenlandia-Australia-Nueva Guinea-Borneo,Groenlandia,"Territorio danés"
Geografía,11,¿Qué país es conocido como la Tierra del Sol Naciente?,China-Corea del Sur-Japón-Tailandia,Japón,"Imperio del Este"
Geografía,12,¿Cuál es el país más poblado del mundo?,India-Estados Unidos-China-Indonesia,China,"Bastión asiático"
Geografía,12,¿En qué país se encuentra el Everest, la montaña más alta del mundo?,Nepal-India-Bhután-Tíbet,Nepal,"Himalaya y alpinismo"
Geografía,12,¿Cuál es el mayor país de América del Sur por área?,Brasil-Argentina-Colombia-Perú,Brasil,"Selva amazónica"
Geografía,13,¿Cuál es el país más grande del mundo por área terrestre?,Rusia-Canadá-China-Estados Unidos,Rusia,"Extensión transcontinental"
Geografía,13,¿En qué país se encuentra el lago Titicaca, el lago navegable más alto del mundo?,Perú-Bolivia-Chile-Ecuador,Bolivia,"Altitud y civilización"
Geografía,13,¿Cuál es la montaña más alta de África?,Monte Kilimanjaro-Monte Elbrús-Monte Everest-Monte Aconcagua,Monte Kilimanjaro,"Pico nevado"
Geografía,14,¿En qué país se encuentra la ciudad de Mecca, el lugar más sagrado del Islam?,Egipto-Arabia Saudita-Irán-Turquía,Arabia Saudita,"Peregrinación musulmana"
Geografía,14,¿Cuál es el país más pequeño de América del Sur por área?,Uruguay-Surinam-Guyana-Ecuador,Surinam,"República ribereña"
Geografía,14,¿En qué país se encuentra el desierto de Gobi?,China-India-Mongolia-Kazajistán,Mongolia,"Estepa y dunas"
Geografía,15,¿Cuál es el río más largo de África?,Nilo-Zambeze-Níger-Congo,Nilo,"Cataratas Victoria"
Geografía,15,¿En qué país se encuentra la selva amazónica, la selva tropical más extensa del mundo?,Brasil-Perú-Colombia-Venezuela,Brasil,"Pulmón verde"
Geografía,15,¿Cuál es el país más grande del mundo por extensión territorial en América Latina?,Brasil-Argentina-México-Chile,Brasil,"Extensión meridional"
Ciencia,1,¿Cuál es el elemento más abundante en la corteza terrestre?,Oxígeno-Silicio-Aluminio-Hierro,Oxígeno,"Componente mineral"
Ciencia,1,¿Qué gas necesitan las plantas para realizar la fotosíntesis?,Dióxido de carbono-Nitrógeno-Oxígeno-Metano,Dióxido de carbono,"Proceso vegetal"
Ciencia,1,¿Cuál es la unidad básica de la herencia genética?,Gen-Cromosoma-ADN-Proteína,ADN,"Ácido nucleico"
Ciencia,1,¿Cuál es la capa más externa de la atmósfera terrestre?,Troposfera-Estratosfera-Mesosfera-Termosfera,Troposfera,"Meteorología"
Ciencia,1,¿Qué tipo de estrella es el Sol?,Enana roja-Enana blanca-Gigante roja-Secuencia principal,Secuencia principal,"Centro solar"
Ciencia,2,¿Cuál es el hueso más largo del cuerpo humano?,Fémur-Húmero-Tibia-Fíbula,Fémur,"Extremidad inferior"
Ciencia,2,¿Cuál es el planeta más grande del Sistema Solar?,Tierra-Marte-Júpiter-Saturno,Júpiter,"Gigante gaseoso"
Ciencia,2,¿Qué unidad de medida se utiliza para medir la electricidad?,Voltio-Amperio-Ohmio-Vatio,Amperio,"Corriente eléctrica"
Ciencia,2,¿Cuál es el ácido presente en las células musculares que causa fatiga muscular?,Ácido acético-Ácido láctico-Ácido cítrico-Ácido sulfúrico,Ácido láctico,"Ejercicio físico"
Ciencia,2,¿Cuál es la partícula subatómica con carga positiva?,Electrón-Protón-Neutrón-Positrón,Protón,"Núcleo atómico"
Ciencia,3,¿Qué tipo de energía es producida por la fusión nuclear en las estrellas como el Sol?,Energía térmica-Energía mecánica-Energía nuclear-Energía solar,Energía nuclear,"Reacción estelar"
Ciencia,3,¿Cuál es la hormona responsable de regular los niveles de glucosa en sangre?,Insulina-Adrenalina-Testosterona-Progesterona,Insulina,"Diabetes"
Ciencia,3,¿Qué órgano del cuerpo humano produce la insulina?,Páncreas-Hígado-Riñón-Corazón,Páncreas,"Sistema endocrino"
Ciencia,3,¿Cuál es la velocidad de la luz en el vacío?,300.000 km/s-500.000 km/s-1.000.000 km/s-750.000 km/s,300.000 km/s,"Constante física"
Ciencia,3,¿Qué gas compone aproximadamente el 78% de la atmósfera terrestre?,Nitrógeno-Oxígeno-Dióxido de carbono-Argón,Nitrógeno,"Respiración y aire"
Ciencia,4,¿Cuál es el órgano más grande del cuerpo humano?,Cerebro-Piel-Hígado-Pulmones,Piel,"Metabolismo"
Ciencia,4,¿Qué proceso biológico convierte la luz solar en energía química en las plantas?,Fotosíntesis-Respiración celular-Transpiración-Fijación de nitrógeno,Fotosíntesis,"Producción vegetal"
Ciencia,4,¿Cuál es el hueso más pequeño del cuerpo humano?,Estribo-Martillo-Yunque-Fémur,Estribo,"Audición y equilibrio"
Ciencia,4,¿Cuál es la capa más interna de la piel humana?,Epidermis-Dermis-Hipodermis-Cutícula,Hipodermis,"Tejido dérmico"
Ciencia,4,¿Qué gas es esencial para la respiración aeróbica de los seres vivos?,Dióxido de carbono-Nitrógeno-Oxígeno-Metano,Oxígeno,"Intercambio pulmonar"
Ciencia,5,¿Qué tipo de roca es el mármol?,Ígnea-Sedimentaria-Metamórfica-Volcánica,Metamórfica,"Proceso geológico"
Ciencia,5,¿Cuál es el proceso natural por el cual se forma el petróleo?,Erosión-Evaporación-Fotosíntesis-Litificación,Litificación,"Residuos orgánicos"
Ciencia,5,¿Qué parte del átomo tiene carga negativa?,Neutrón-Protón-Electrón-Positrón,Electrón,"Partícula elemental"
Ciencia,5,¿Cuál es la rama de la biología que estudia los organismos y su ambiente?,Botánica-Zoología-Ecología-Micología,Ecología,"Relaciones naturales"
Ciencia,5,¿Cuál es el proceso mediante el cual las plantas pierden agua a través de sus hojas?,Transpiración-Fotosíntesis-Evaporación-Absorción,Transpiración,"Ciclo vegetal"
Ciencia,6,¿Cuál es el hueso más duro del cuerpo humano?,Fémur-Mandíbula-Estribo-Omóplato,Mandíbula,"Dentición y masticación"
Ciencia,6,¿Cuál es la célula más pequeña del cuerpo humano?,Célula nerviosa-Célula ósea-Célula sanguínea-Célula espermática,Célula sanguínea,"Componente vital"
Ciencia,6,¿Qué parte del cuerpo humano es afectada por la miopía?,Oído-Ojo-Nariz-Boca,Ojo,"Visión borrosa"
Ciencia,6,¿Qué órgano produce la bilis para ayudar en la digestión de las grasas?,Hígado-Páncreas-Intestino-Estómago,Hígado,"Sistema digestivo"
Ciencia,6,¿Cuál es la principal función de la hemoglobina en el cuerpo humano?,Transportar oxígeno-Regular la temperatura-Producir energía-Proteger contra enfermedades,Transportar oxígeno,"Hematología"
Ciencia,7,¿Cuál es la unidad básica de la estructura de los seres vivos?,Célula-Tejido-Órgano-Sistema,Célula,"Biología celular"
Ciencia,7,¿Qué tipo de ácido esencial se encuentra en los cítricos como las naranjas y limones?,Ácido acético-Ácido cítrico-Ácido láctico-Ácido fólico,Ácido cítrico,"Frutas y sabor"
Ciencia,7,¿Qué parte del sistema nervioso es responsable del pensamiento racional y la toma de decisiones?,Cerebelo-Cerebro-Médula espinal-Ganglios,Cerebro,"Cognición y percepción"
Ciencia,8,¿Cuál es la unidad básica de la herencia genética?,Gen-Cromosoma-ADN-Proteína,ADN,"Ácido nucleico"
Ciencia,8,¿Cuál es la capa más externa de la atmósfera terrestre?,Troposfera-Estratosfera-Mesosfera-Termosfera,Troposfera,"Meteorología"
Ciencia,8,¿Qué tipo de estrella es el Sol?,Enana roja-Enana blanca-Gigante roja-Secuencia principal,Secuencia principal,"Centro solar"
Ciencia,9,¿Cuál es el hueso más largo del cuerpo humano?,Fémur-Húmero-Tibia-Fíbula,Fémur,"Extremidad inferior"
Ciencia,9,¿Cuál es el planeta más grande del Sistema Solar?,Tierra-Marte-Júpiter-Saturno,Júpiter,"Gigante gaseoso"
Ciencia,9,¿Qué unidad de medida se utiliza para medir la electricidad?,Voltio-Amperio-Ohmio-Vatio,Amperio,"Corriente eléctrica"
Ciencia,10,¿Cuál es el ácido presente en las células musculares que causa fatiga muscular?,Ácido acético-Ácido láctico-Ácido cítrico-Ácido sulfúrico,Ácido láctico,"Ejercicio físico"
Ciencia,10,¿Cuál es la partícula subatómica con carga positiva?,Electrón-Protón-Neutrón-Positrón,Protón,"Núcleo atómico"
Ciencia,10,¿Qué tipo de energía es producida por la fusión nuclear en las estrellas como el Sol?,Energía térmica-Energía mecánica-Energía nuclear-Energía solar,Energía nuclear,"Reacción estelar"
Ciencia,11,¿Cuál es la hormona responsable de regular los niveles de glucosa en sangre?,Insulina-Adrenalina-Testosterona-Progesterona,Insulina,"Diabetes"
Ciencia,11,¿Qué órgano del cuerpo humano produce la insulina?,Páncreas-Hígado-Riñón-Corazón,Páncreas,"Sistema endocrino"
Ciencia,11,¿Cuál es la velocidad de la luz en el vacío?,300.000 km/s-500.000 km/s-1.000.000 km/s-750.000 km/s,300.000 km/s,"Constante física"
Ciencia,12,¿Cuál es el proceso natural por el cual se forma el petróleo?,Erosión-Evaporación-Fotosíntesis-Litificación,Litificación,"Residuos orgánicos"
Ciencia,12,¿Qué parte del átomo tiene carga negativa?,Neutrón-Protón-Electrón-Positrón,Electrón,"Partícula elemental"
Ciencia,12,¿Cuál es el proceso mediante el cual las plantas pierden agua a través de sus hojas?,Transpiración-Fotosíntesis-Evaporación-Absorción,Transpiración,"Ciclo vegetal"
Ciencia,13,¿Cuál es la célula más pequeña del cuerpo humano?,Célula nerviosa-Célula ósea-Célula sanguínea-Célula espermática,Célula sanguínea,"Componente vital"
Ciencia,13,¿Qué órgano produce la bilis para ayudar en la digestión de las grasas?,Hígado-Páncreas-Intestino-Estómago,Hígado,"Sistema digestivo"
Ciencia,13,¿Cuál es la principal función de la hemoglobina en el cuerpo humano?,Transportar oxígeno-Regular la temperatura-Producir energía-Proteger contra enfermedades,Transportar oxígeno,"Hematología"
Ciencia,14,¿Qué tipo de ácido esencial se encuentra en los cítricos como las naranjas y limones?,Ácido acético-Ácido cítrico-Ácido láctico-Ácido fólico,Ácido cítrico,"Frutas y sabor"
Ciencia,14,¿Qué parte del sistema nervioso es responsable del pensamiento racional y la toma de decisiones?,Cerebelo-Cerebro-Médula espinal-Ganglios,Cerebro,"Cognición y percepción"
Ciencia,14,¿Cuál es la unidad básica de la estructura de los seres vivos?,Célula-Tejido-Órgano-Sistema,Célula,"Biología celular"
Ciencia,15,¿Cuál es el proceso natural por el cual se forma el petróleo?,Erosión-Evaporación-Fotosíntesis-Litificación,Litificación,"Residuos orgánicos"
Ciencia,15,¿Qué parte del átomo tiene carga negativa?,Neutrón-Protón-Electrón-Positrón,Electrón,"Partícula elemental"
Ciencia,15,¿Cuál es el proceso mediante el cual las plantas pierden agua a través de sus hojas?,Transpiración-Fotosíntesis-Evaporación-Absorción,Transpiración,"Ciclo vegetal"
